use std::path::PathBuf;

use clap::Parser;

#[derive(Parser)]
#[clap(name = "Ferris Keymap Visualizer")]
#[clap(author, version, about)]
pub struct Args {
    /// The keymap.json file which is generated by QMK.
    pub keymap: PathBuf,
    /// The layer of the keymap that is to be visualized
    pub layer: usize,

    /// Name of the output file
    #[clap(short, long, parse(from_os_str), value_name = "PATH")]
    pub image: Option<PathBuf>,
}
